#!/usr/bin/env python
# -*- coding: utf8 -*-
# *****************************************************************
# **       PTS -- Python Toolkit for working with SKIRT          **
# **       © Astronomical Observatory, Ghent University          **
# *****************************************************************

## \package pts.core.prep.upgradeskifile Upgrade a ski file to the latest format version
#
# The function in this module upgrades a ski file to the latest format version.
# Any ski file generated by a SKIRT6 built from the repository source after January 1, 2013
# should be propertly adjusted to the most recent format version (at least, that's the goal).
#

# -----------------------------------------------------------------

# Import standard modules
import os
import os.path
from datetime import datetime

# Import the relevant PTS classes and modules
from ..simulation.skifile import SkiFile

# -----------------------------------------------------------------

## This function upgrades the specified ski file to the latest format version, if needed. The function
# operates in one of two modes, depending on the number of filename arguments given. The specified filenames
# should have the ".ski" or ".xml" extension and may include an absolute or relative path.
#
# If only one argument is given, and the specified ski file needs an update, the original ski file is
# overwritten with the upgraded version, and a backup copy of the original ski file is placed next to it.
# The name of the backup copy (if one is made) includes a time stamp and has the ".xml" filename extension.
# The function returns true if the ski file was upgraded (and a backup copy was made), false otherwise.
#
# If two arguments are given, the source file remains untouched and a new, possibly upgraded ski file
# is placed at the target filepath, overwriting any existing file. No extra backup is made.
# The function returns true if the target ski file was upgraded, false otherwise.
#
def upgradeskifile(skifile, targetfile=None):
    skifile = os.path.expanduser(skifile)
    assert skifile.endswith((".ski",".xml"))

    # define the upgrade conditions and transforms
    upgrades = _get_upgrade_definitions()

    # open the ski file and apply the upgrades if needed
    ski = SkiFile(skifile)
    changed = False
    for condition,templates in upgrades:
        changed |= ski.transformif(condition, templates)

    # single argument: if there were changes, make a backup copy and save the updated file over the original
    if targetfile==None and changed:
        backup = skifile[:-4] + "_" + datetime.now().strftime("%Y-%m-%d--%H-%M-%S") + "_backupski.xml"
        os.rename(skifile, backup)
        ski.saveto(skifile)

    # two arguments: save into the target file
    if targetfile!=None:
        ski.saveto(targetfile)

    return changed

# -----------------------------------------------------------------

## This private function returns a sequence of 2-tuples, each defining the XPath condition and XSLT templates
# for a single modification to the ski file format. The svn/git revision number listed for each item identifies
# the change in the SKIRT code requiring that ski file modification.
def _get_upgrade_definitions():

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # ***** SKIRT 7 upgrades *****
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # start the list of SKIRT 7 definitions
    definitions = [

    # svn 302: in binary tree dust grids, replace the barycentric attribute by the directionMethod attribute
    # using an appropriate enumeration value depending on the original attribute value
    ('''//BinTreeDustGridStructure/@barycentric''',
    '''
    <xsl:template match="//BinTreeDustGridStructure/@barycentric">
        <xsl:attribute name="directionMethod">
            <xsl:choose>
                <xsl:when test="number()=1 or starts-with(.,'t') or starts-with(.,'T') or starts-with(.,'y') or starts-with(.,'Y')">
                    <xsl:value-of select="'Barycenter'"/>
                </xsl:when>
                <xsl:otherwise>
                    <xsl:value-of select="'Alternating'"/>
                </xsl:otherwise>
            </xsl:choose>
        </xsl:attribute>
    </xsl:template>
    '''),

    # svn 356: in SEDInstrument elements, remove the attributes pixelsX, extentX, pixelsY, extentY
    ('''//SEDInstrument/@pixelsX | //SEDInstrument/@extentX | //SEDInstrument/@pixelsY | //SEDInstrument/@extentY''',
    '''
    <xsl:template match="//SEDInstrument/@pixelsX | //SEDInstrument/@extentX | //SEDInstrument/@pixelsY | //SEDInstrument/@extentY">
    </xsl:template>
    '''),

    # svn 441: in AdaptiveMeshXxxx elements, move the filename attribute to a nested element
    ('''//AdaptiveMeshDustDistribution/@filename | //AdaptiveMeshDustGeometry/@filename | //AdaptiveMeshStellarSystem/@filename''',
    '''
    <xsl:template match="//AdaptiveMeshDustDistribution | //AdaptiveMeshDustGeometry | //AdaptiveMeshStellarSystem">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
            <xsl:element name="adaptiveMeshFile">
                <xsl:attribute name="type">
                    <xsl:value-of select="'AdaptiveMeshFile'"/>
                </xsl:attribute>
                <xsl:element name="AdaptiveMeshAsciiFile">
                    <xsl:attribute name="filename">
                        <xsl:value-of select="@filename"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:copy>
    </xsl:template>
    <xsl:template match="//AdaptiveMeshDustDistribution/@filename | //AdaptiveMeshDustGeometry/@filename | //AdaptiveMeshStellarSystem/@filename">
    </xsl:template>
    '''),

    # svn 495: replace OligoDustMix elements by InterstellarDustMix elements
    ('''//OligoDustMix''',
    '''
    <xsl:template match="OligoDustMix">
        <xsl:element name="InterstellarDustMix">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    '''),

    # svn 547: replace AdaptiveMeshDustComponent elements by MeshDustComponent elements
    ('''//AdaptiveMeshDustComponent''',
    '''
    <xsl:template match="AdaptiveMeshDustDistribution/components/@type">
        <xsl:attribute name="type">
            <xsl:value-of select="'MeshDustComponent'"/>
        </xsl:attribute>
    </xsl:template>
    <xsl:template match="AdaptiveMeshDustComponent">
        <xsl:element name="MeshDustComponent">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    '''),

    # svn 580: replace StellarGeometry elements by Geometry elements
    ('''//geometry[@type='StellarGeometry']''',
    '''
    <xsl:template match="geometry[@type='StellarGeometry']/@type">
        <xsl:attribute name="type">
            <xsl:value-of select="'Geometry'"/>
        </xsl:attribute>
    </xsl:template>
    <xsl:template match="CentralStarStellarGeometry">
        <xsl:element name="PointGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="GaussianStellarGeometry">
        <xsl:element name="GaussianGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="GammaStellarGeometry">
        <xsl:element name="GammaGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="PlummerStellarGeometry">
        <xsl:element name="PlummerGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="SersicStellarGeometry">
        <xsl:element name="SersicGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="ExpDiskStellarGeometry">
        <xsl:element name="ExpDiskGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="TruncatedExpDiskStellarGeometry">
        <xsl:element name="ExpDiskGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="ExpDiskSpiralArmsStellarGeometry">
        <xsl:element name="ExpDiskSpiralArmsGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="FlattenedGammaStellarGeometry">
        <xsl:element name="SpheroidalGeometry">
            <xsl:apply-templates select="@*[name()='flattening']"/>
            <xsl:element name="geometry">
                <xsl:attribute name="type">
                    <xsl:value-of select="'SpheGeometry'"/>
                </xsl:attribute>
                <xsl:element name="GammaGeometry">
                    <xsl:apply-templates select="@*[name()!='flattening']|node()"/>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    <xsl:template match="FlattenedPlummerStellarGeometry">
        <xsl:element name="SpheroidalGeometry">
            <xsl:apply-templates select="@*[name()='flattening']"/>
            <xsl:element name="geometry">
                <xsl:attribute name="type">
                    <xsl:value-of select="'SpheGeometry'"/>
                </xsl:attribute>
                <xsl:element name="PlummerGeometry">
                    <xsl:apply-templates select="@*[name()!='flattening']|node()"/>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    <xsl:template match="FlattenedSersicStellarGeometry">
        <xsl:element name="SpheroidalGeometry">
            <xsl:apply-templates select="@*[name()='flattening']"/>
            <xsl:element name="geometry">
                <xsl:attribute name="type">
                    <xsl:value-of select="'SpheGeometry'"/>
                </xsl:attribute>
                <xsl:element name="SersicGeometry">
                    <xsl:apply-templates select="@*[name()!='flattening']|node()"/>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    <xsl:template match="PseudoSersicStellarGeometry">
        <xsl:element name="SpheroidalGeometry">
            <xsl:apply-templates select="@*[name()='flattening']"/>
            <xsl:element name="geometry">
                <xsl:attribute name="type">
                    <xsl:value-of select="'SpheGeometry'"/>
                </xsl:attribute>
                <xsl:element name="PseudoSersicGeometry">
                    <xsl:apply-templates select="@*[name()!='flattening']|node()"/>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    <xsl:template match="MGEStellarGeometry">
        <xsl:element name="MGEGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="AdaptiveMeshStellarGeometry">
        <xsl:element name="AdaptiveMeshGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="VoronoiStellarGeometry">
        <xsl:element name="VoronoiGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="OffsetStellarGeometry">
        <xsl:element name="OffsetGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    '''),

    # svn 580: replace DustGeometry elements by Geometry elements
    ('''//geometry[@type='DustGeometry']''',
    '''
    <xsl:template match="geometry[@type='DustGeometry']/@type">
        <xsl:attribute name="type">
            <xsl:value-of select="'Geometry'"/>
        </xsl:attribute>
    </xsl:template>
    <xsl:template match="PlummerDustGeometry">
        <xsl:element name="PlummerGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="SersicDustGeometry">
        <xsl:element name="SersicGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="ShellDustGeometry">
        <xsl:element name="ShellGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="ExpDiskDustGeometry">
        <xsl:element name="ExpDiskGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="TruncatedExpDiskDustGeometry">
        <xsl:element name="ExpDiskGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="ExpDiskSpiralArmsDustGeometry">
        <xsl:element name="ExpDiskSpiralArmsGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="TTauriDiskDustGeometry">
        <xsl:element name="TTauriDiskGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="FlattenedPlummerDustGeometry">
        <xsl:element name="SpheroidalGeometry">
            <xsl:apply-templates select="@*[name()='flattening']"/>
            <xsl:element name="geometry">
                <xsl:attribute name="type">
                    <xsl:value-of select="'SpheGeometry'"/>
                </xsl:attribute>
                <xsl:element name="PlummerGeometry">
                    <xsl:apply-templates select="@*[name()!='flattening']|node()"/>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    <xsl:template match="FlattenedSersicDustGeometry">
        <xsl:element name="SpheroidalGeometry">
            <xsl:apply-templates select="@*[name()='flattening']"/>
            <xsl:element name="geometry">
                <xsl:attribute name="type">
                    <xsl:value-of select="'SpheGeometry'"/>
                </xsl:attribute>
                <xsl:element name="SersicGeometry">
                    <xsl:apply-templates select="@*[name()!='flattening']|node()"/>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    <xsl:template match="PseudoSersicDustGeometry">
        <xsl:element name="SpheroidalGeometry">
            <xsl:apply-templates select="@*[name()='flattening']"/>
            <xsl:element name="geometry">
                <xsl:attribute name="type">
                    <xsl:value-of select="'SpheGeometry'"/>
                </xsl:attribute>
                <xsl:element name="PseudoSersicGeometry">
                    <xsl:apply-templates select="@*[name()!='flattening']|node()"/>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    <xsl:template match="RingDustGeometry">
        <xsl:element name="RingGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="TorusDustGeometry">
        <xsl:element name="TorusGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="ClumpyTorusDustGeometry">
        <xsl:element name="ClumpyGeometry">
            <xsl:apply-templates select="@*[name()='clumpFraction']|@*[name()='clumpCount']|@*[name()='clumpRadius']"/>
            <xsl:element name="kernel">
                <xsl:attribute name="type">
                    <xsl:value-of select="'SmoothingKernel'"/>
                </xsl:attribute>
                <xsl:element name="CubicSplineSmoothingKernel"/>
            </xsl:element>
            <xsl:element name="geometry">
                <xsl:attribute name="type">
                    <xsl:value-of select="'Geometry'"/>
                </xsl:attribute>
                <xsl:element name="TorusGeometry">
                    <xsl:attribute name="expon">
                        <xsl:value-of select="@smoothExpon"/>
                    </xsl:attribute>
                    <xsl:attribute name="index">
                        <xsl:value-of select="@smoothIndex"/>
                    </xsl:attribute>
                    <xsl:apply-templates select="@*[name()='openAngle']|@*[name()='minRadius']|@*[name()='maxRadius']"/>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    <xsl:template match="ClumpyExpDiskDustGeometry">
        <xsl:element name="ClumpyGeometry">
            <xsl:apply-templates select="@*[name()='clumpFraction']|@*[name()='clumpCount']|@*[name()='clumpRadius']"/>
            <xsl:element name="kernel">
                <xsl:attribute name="type">
                    <xsl:value-of select="'SmoothingKernel'"/>
                </xsl:attribute>
                <xsl:element name="CubicSplineSmoothingKernel"/>
            </xsl:element>
            <xsl:element name="geometry">
                <xsl:attribute name="type">
                    <xsl:value-of select="'Geometry'"/>
                </xsl:attribute>
                <xsl:element name="ExpDiskGeometry">
                    <xsl:attribute name="radialScale">
                        <xsl:value-of select="@radialScaleSmooth"/>
                    </xsl:attribute>
                    <xsl:attribute name="axialScale">
                        <xsl:value-of select="@axialScaleSmooth"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    <xsl:template match="ClumpyExpDiskSpiralArmsDustGeometry">
        <xsl:element name="ClumpyGeometry">
            <xsl:apply-templates select="@*[name()='clumpFraction']|@*[name()='clumpCount']|@*[name()='clumpRadius']"/>
            <xsl:element name="kernel">
                <xsl:attribute name="type">
                    <xsl:value-of select="'SmoothingKernel'"/>
                </xsl:attribute>
                <xsl:element name="CubicSplineSmoothingKernel"/>
            </xsl:element>
            <xsl:element name="geometry">
                <xsl:attribute name="type">
                    <xsl:value-of select="'Geometry'"/>
                </xsl:attribute>
                <xsl:element name="ExpDiskSpiralArmsGeometry">
                    <xsl:attribute name="radialScale">
                        <xsl:value-of select="@radialScaleSmooth"/>
                    </xsl:attribute>
                    <xsl:attribute name="axialScale">
                        <xsl:value-of select="@axialScaleSmooth"/>
                    </xsl:attribute>
                    <xsl:attribute name="arms">
                        <xsl:value-of select="@armsSmooth"/>
                    </xsl:attribute>
                    <xsl:attribute name="pitch">
                        <xsl:value-of select="@pitchSmooth"/>
                    </xsl:attribute>
                    <xsl:attribute name="perturbWeight">
                        <xsl:value-of select="@perturbWeightSmooth"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    <xsl:template match="MGEDustGeometry">
        <xsl:element name="MGEGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="AdaptiveMeshDustGeometry">
        <xsl:element name="AdaptiveMeshGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="VoronoiDustGeometry">
        <xsl:element name="VoronoiGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="OffsetDustGeometry">
        <xsl:element name="OffsetGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="Trust7aDustGeometry">
        <xsl:element name="Trust7aGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="Trust7bDustGeometry">
        <xsl:element name="Trust7bGeometry">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    '''),

    # svn 603: replace PanDustSystem attributes dustEmission and transient by nested elements
    ('''//PanDustSystem/@dustEmission | //PanDustSystem/@transient''',
    '''
    <xsl:template match="//PanDustSystem">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
            <xsl:if test="number(@dustEmission)=1 or starts-with(@dustEmission,'t') or starts-with(@dustEmission,'T') or starts-with(@dustEmission,'y') or starts-with(@dustEmission,'Y')">
                <xsl:choose>
                    <xsl:when test="number(@transient)=1 or starts-with(@transient,'t') or starts-with(@transient,'T') or starts-with(@transient,'y') or starts-with(@transient,'Y')">
                        <xsl:element name="dustEmissivity">
                            <xsl:attribute name="type">
                                <xsl:value-of select="'DustEmissivity'"/>
                            </xsl:attribute>
                            <xsl:element name="DustEmDustEmissivity"/>
                        </xsl:element>
                        <xsl:element name="dustLib">
                            <xsl:attribute name="type">
                                <xsl:value-of select="'DustLib'"/>
                            </xsl:attribute>
                            <xsl:element name="Dim2DustLib"/>
                        </xsl:element>
                    </xsl:when>
                    <xsl:otherwise>
                        <xsl:element name="dustEmissivity">
                            <xsl:attribute name="type">
                                <xsl:value-of select="'DustEmissivity'"/>
                            </xsl:attribute>
                            <xsl:element name="GreyBodyDustEmissivity"/>
                        </xsl:element>
                        <xsl:element name="dustLib">
                            <xsl:attribute name="type">
                                <xsl:value-of select="'DustLib'"/>
                            </xsl:attribute>
                            <xsl:element name="Dim1DustLib"/>
                        </xsl:element>
                    </xsl:otherwise>
                </xsl:choose>
            </xsl:if>
        </xsl:copy>
    </xsl:template>
    <xsl:template match="//PanDustSystem/@dustEmission | //PanDustSystem/@transient">
    </xsl:template>
    '''),

    # git 42 (June 26, 2014): replace CompStellarSystem element by identical StellarSystem element
    ('''//CompStellarSystem''',
    '''
    <xsl:template match="CompStellarSystem">
        <xsl:element name="StellarSystem">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    '''),

    # git 42 (June 26, 2014): replace SPH/AdaptiveMesh/VoronoiStellarSystem element by StellarSystem element
    #                         with nested SPH/AdaptiveMesh/VoronoiStellarComp
    ('''//SPHStellarSystem''',
    '''
    <xsl:template match="SPHStellarSystem">
        <xsl:element name="StellarSystem">
            <xsl:element name="components">
                <xsl:attribute name="type">
                    <xsl:value-of select="'StellarComp'"/>
                </xsl:attribute>
                <xsl:element name="SPHStellarComp">
                    <xsl:apply-templates select="@*|node()"/>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),
    ('''//AdaptiveMeshStellarSystem''',
    '''
    <xsl:template match="AdaptiveMeshStellarSystem">
        <xsl:element name="StellarSystem">
            <xsl:element name="components">
                <xsl:attribute name="type">
                    <xsl:value-of select="'StellarComp'"/>
                </xsl:attribute>
                <xsl:element name="AdaptiveMeshStellarComp">
                    <xsl:apply-templates select="@*|node()"/>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),
    ('''//VoronoiStellarSystem''',
    '''
    <xsl:template match="VoronoiStellarSystem">
        <xsl:element name="StellarSystem">
            <xsl:element name="components">
                <xsl:attribute name="type">
                    <xsl:value-of select="'StellarComp'"/>
                </xsl:attribute>
                <xsl:element name="VoronoiStellarComp">
                    <xsl:apply-templates select="@*|node()"/>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # git 68: in ZubkoGraphiteGrainSizeDistribution elements, remove the attributes minSize and maxSize
    ('''//ZubkoPAHGrainSizeDistribution/@minSize | //ZubkoPAHGrainSizeDistribution/@maxSize |
        //ZubkoGraphiteGrainSizeDistribution/@minSize | //ZubkoGraphiteGrainSizeDistribution/@maxSize |
        //ZubkoSilicateGrainSizeDistribution/@minSize | //ZubkoSilicateGrainSizeDistribution/@maxSize''',
    '''
    <xsl:template match="//ZubkoPAHGrainSizeDistribution/@minSize | //ZubkoPAHGrainSizeDistribution/@maxSize">
    </xsl:template>
    <xsl:template match="//ZubkoGraphiteGrainSizeDistribution/@minSize | //ZubkoGraphiteGrainSizeDistribution/@maxSize">
    </xsl:template>
    <xsl:template match="//ZubkoSilicateGrainSizeDistribution/@minSize | //ZubkoSilicateGrainSizeDistribution/@maxSize">
    </xsl:template>
    '''),

    # git 101: remove ExpDiskSpiralArmsGeometry; use SpiralStructureGeometry decorator instead
    ('''//ExpDiskSpiralArmsGeometry''',
    '''
    <xsl:template match="ExpDiskSpiralArmsGeometry">
        <xsl:element name="SpiralStructureGeometry">
            <xsl:attribute name="radius">
                <xsl:value-of select="@radialScale"/>
            </xsl:attribute>
            <xsl:apply-templates select="@*[name()='arms']|@*[name()='pitch']|@*[name()='phase']|@*[name()='perturbWeight']"/>
            <xsl:element name="geometry">
                <xsl:attribute name="type">
                    <xsl:value-of select="'AxGeometry'"/>
                </xsl:attribute>
                <xsl:element name="ExpDiskGeometry">
                    <xsl:apply-templates select="@*[name()='radialScale']|@*[name()='axialScale']|@*[name()='radialTrunc']|@*[name()='axialTrunc']"/>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # git 324 (Jan 9, 2015): rename geometry decorator classes to end in "Decorator"
    ('''//OffsetGeometry | //RotateGeometry | //SpheroidalGeometry | //TriaxialGeometry |
        //SphericalHoleGeometry | //SpiralStructureGeometry | //ClumpyGeometry | //FoamDecoGeometry''',
    '''
    <xsl:template match="OffsetGeometry">
        <xsl:element name="OffsetGeometryDecorator">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="RotateGeometry">
        <xsl:element name="RotateGeometryDecorator">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="SpheroidalGeometry">
        <xsl:element name="SpheroidalGeometryDecorator">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="TriaxialGeometry">
        <xsl:element name="TriaxialGeometryDecorator">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="SphericalHoleGeometry">
        <xsl:element name="SphericalCavityGeometryDecorator">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="SpiralStructureGeometry">
        <xsl:element name="SpiralStructureGeometryDecorator">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="ClumpyGeometry">
        <xsl:element name="ClumpyGeometryDecorator">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="FoamDecoGeometry">
        <xsl:element name="FoamGeometryDecorator">
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    '''),

    # git 497 (Jul 8, 2015): merge SPHStarburstComp into SPHStellarComp
    ('''//SPHStarburstComp''',
    '''
    <xsl:template match="SPHStarburstComp">
        <xsl:element name="SPHStellarComp">
            <xsl:apply-templates select="@*|node()"/>
            <xsl:element name="sedFamily">
                <xsl:attribute name="type">
                    <xsl:value-of select="'SEDFamily'"/>
                </xsl:attribute>
                <xsl:element name="MappingsSEDFamily">
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # - - - - - - - - - - - -
    # git 577-0008afd (Oct 22, 2015): new dust grid class hiearchy using meshes; instruments with field of view

    # remove "Structure" from name and type of dustGridStructure property
    ('''//dustGridStructure''',
    '''
    <xsl:template match="dustGridStructure">
        <xsl:element name="dustGrid">
            <xsl:attribute name="type">
                <xsl:value-of select="'DustGrid'"/>
            </xsl:attribute>
            <xsl:apply-templates select="node()"/>
        </xsl:element>
    </xsl:template>
    '''),

    # replace LinSpheDustGridStructure by Sphere1DDustGrid
    ('''//LinSpheDustGridStructure''',
    '''
    <xsl:template match="LinSpheDustGridStructure">
        <xsl:element name="Sphere1DDustGrid">
            <xsl:apply-templates select="@*[starts-with(name(),'write')]"/>
            <xsl:attribute name="maxR">
                <xsl:value-of select="@extent"/>
            </xsl:attribute>
            <xsl:element name="meshR">
                <xsl:attribute name="type">
                    <xsl:value-of select="'Mesh'"/>
                </xsl:attribute>
                <xsl:element name="LinMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@points"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # replace PowSpheDustGridStructure by Sphere1DDustGrid
    ('''//PowSpheDustGridStructure''',
    '''
    <xsl:template match="PowSpheDustGridStructure">
        <xsl:element name="Sphere1DDustGrid">
            <xsl:apply-templates select="@*[starts-with(name(),'write')]"/>
            <xsl:attribute name="maxR">
                <xsl:value-of select="@extent"/>
            </xsl:attribute>
            <xsl:element name="meshR">
                <xsl:attribute name="type">
                    <xsl:value-of select="'Mesh'"/>
                </xsl:attribute>
                <xsl:element name="PowMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@points"/>
                    </xsl:attribute>
                    <xsl:attribute name="ratio">
                        <xsl:value-of select="@ratio"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # replace LogSpheDustGridStructure by Sphere1DDustGrid
    ('''//LogSpheDustGridStructure''',
    '''
    <xsl:template match="LogSpheDustGridStructure">
        <xsl:element name="Sphere1DDustGrid">
            <xsl:apply-templates select="@*[starts-with(name(),'write')]"/>
            <xsl:attribute name="maxR">
                <xsl:value-of select="@outerExtent"/>
            </xsl:attribute>
            <xsl:element name="meshR">
                <xsl:attribute name="type">
                    <xsl:value-of select="'Mesh'"/>
                </xsl:attribute>
                <xsl:element name="LogMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@points"/>
                    </xsl:attribute>
                    <xsl:attribute name="centralBinFraction">
                        <xsl:value-of select="substring-before(normalize-space(@innerExtent),' ') div substring-before(normalize-space(@outerExtent),' ')"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # replace LogLinAxSpheDustGridStructure by Sphere2DDustGrid
    ('''//LogLinAxSpheDustGridStructure''',
    '''
    <xsl:template match="LogLinAxSpheDustGridStructure">
        <xsl:element name="Sphere2DDustGrid">
            <xsl:apply-templates select="@*[starts-with(name(),'write')]"/>
            <xsl:attribute name="maxR">
                <xsl:value-of select="@radialOuterExtent"/>
            </xsl:attribute>
            <xsl:element name="meshR">
                <xsl:attribute name="type">
                    <xsl:value-of select="'Mesh'"/>
                </xsl:attribute>
                <xsl:element name="LogMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@radialPoints"/>
                    </xsl:attribute>
                    <xsl:attribute name="centralBinFraction">
                        <xsl:value-of select="substring-before(normalize-space(@radialInnerExtent),' ') div substring-before(normalize-space(@radialOuterExtent),' ')"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
            <xsl:element name="meshTheta">
                <xsl:attribute name="type">
                    <xsl:value-of select="'Mesh'"/>
                </xsl:attribute>
                <xsl:element name="LinMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@angularPoints"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # replace LinAxDustGridStructure by Cylinder2DDustGrid
    ('''//LinAxDustGridStructure''',
    '''
    <xsl:template match="LinAxDustGridStructure">
        <xsl:element name="Cylinder2DDustGrid">
            <xsl:apply-templates select="@*[starts-with(name(),'write')]"/>
            <xsl:attribute name="maxR">
                <xsl:value-of select="@radialExtent"/>
            </xsl:attribute>
            <xsl:attribute name="minZ">
                <xsl:value-of select="concat('-',@axialExtent)"/>
            </xsl:attribute>
            <xsl:attribute name="maxZ">
                <xsl:value-of select="@axialExtent"/>
            </xsl:attribute>
            <xsl:element name="meshR">
                <xsl:attribute name="type">
                    <xsl:value-of select="'Mesh'"/>
                </xsl:attribute>
                <xsl:element name="LinMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@radialPoints"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
            <xsl:element name="meshZ">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="LinMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@axialPoints"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # replace PowAxDustGridStructure by Cylinder2DDustGrid
    ('''//PowAxDustGridStructure''',
    '''
    <xsl:template match="PowAxDustGridStructure">
        <xsl:element name="Cylinder2DDustGrid">
            <xsl:apply-templates select="@*[starts-with(name(),'write')]"/>
            <xsl:attribute name="maxR">
                <xsl:value-of select="@radialExtent"/>
            </xsl:attribute>
            <xsl:attribute name="minZ">
                <xsl:value-of select="concat('-',@axialExtent)"/>
            </xsl:attribute>
            <xsl:attribute name="maxZ">
                <xsl:value-of select="@axialExtent"/>
            </xsl:attribute>
            <xsl:element name="meshR">
                <xsl:attribute name="type">
                    <xsl:value-of select="'Mesh'"/>
                </xsl:attribute>
                <xsl:element name="PowMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@radialPoints"/>
                    </xsl:attribute>
                    <xsl:attribute name="ratio">
                        <xsl:value-of select="@radialRatio"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
            <xsl:element name="meshZ">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="SymPowMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@axialPoints"/>
                    </xsl:attribute>
                    <xsl:attribute name="ratio">
                        <xsl:value-of select="@axialRatio"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # replace LogLinAxDustGridStructure by Cylinder2DDustGrid
    ('''//LogLinAxDustGridStructure''',
    '''
    <xsl:template match="LogLinAxDustGridStructure">
        <xsl:element name="Cylinder2DDustGrid">
            <xsl:apply-templates select="@*[starts-with(name(),'write')]"/>
            <xsl:attribute name="maxR">
                <xsl:value-of select="@radialOuterExtent"/>
            </xsl:attribute>
            <xsl:attribute name="minZ">
                <xsl:value-of select="concat('-',@axialExtent)"/>
            </xsl:attribute>
            <xsl:attribute name="maxZ">
                <xsl:value-of select="@axialExtent"/>
            </xsl:attribute>
            <xsl:element name="meshR">
                <xsl:attribute name="type">
                    <xsl:value-of select="'Mesh'"/>
                </xsl:attribute>
                <xsl:element name="LogMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@radialPoints"/>
                    </xsl:attribute>
                    <xsl:attribute name="centralBinFraction">
                        <xsl:value-of select="substring-before(normalize-space(@radialInnerExtent),' ') div substring-before(normalize-space(@radialOuterExtent),' ')"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
            <xsl:element name="meshZ">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="LinMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@axialPoints"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # replace LogPowAxDustGridStructure by Cylinder2DDustGrid
    ('''//LogPowAxDustGridStructure''',
    '''
    <xsl:template match="LogPowAxDustGridStructure">
        <xsl:element name="Cylinder2DDustGrid">
            <xsl:apply-templates select="@*[starts-with(name(),'write')]"/>
            <xsl:attribute name="maxR">
                <xsl:value-of select="@radialOuterExtent"/>
            </xsl:attribute>
            <xsl:attribute name="minZ">
                <xsl:value-of select="concat('-',@axialExtent)"/>
            </xsl:attribute>
            <xsl:attribute name="maxZ">
                <xsl:value-of select="@axialExtent"/>
            </xsl:attribute>
            <xsl:element name="meshR">
                <xsl:attribute name="type">
                    <xsl:value-of select="'Mesh'"/>
                </xsl:attribute>
                <xsl:element name="LogMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@radialPoints"/>
                    </xsl:attribute>
                    <xsl:attribute name="centralBinFraction">
                        <xsl:value-of select="substring-before(normalize-space(@radialInnerExtent),' ') div substring-before(normalize-space(@radialOuterExtent),' ')"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
            <xsl:element name="meshZ">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="SymPowMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@axialPoints"/>
                    </xsl:attribute>
                    <xsl:attribute name="ratio">
                        <xsl:value-of select="@axialRatio"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # replace LinCubDustGridStructure by CartesianDustGrid
    ('''//LinCubDustGridStructure''',
    '''
    <xsl:template match="LinCubDustGridStructure">
        <xsl:element name="CartesianDustGrid">
            <xsl:apply-templates select="@*[starts-with(name(),'write')]"/>
            <xsl:attribute name="minX">
                <xsl:value-of select="concat('-',@extentX)"/>
            </xsl:attribute>
            <xsl:attribute name="maxX">
                <xsl:value-of select="@extentX"/>
            </xsl:attribute>
            <xsl:attribute name="minY">
                <xsl:value-of select="concat('-',@extentY)"/>
            </xsl:attribute>
            <xsl:attribute name="maxY">
                <xsl:value-of select="@extentY"/>
            </xsl:attribute>
            <xsl:attribute name="minZ">
                <xsl:value-of select="concat('-',@extentZ)"/>
            </xsl:attribute>
            <xsl:attribute name="maxZ">
                <xsl:value-of select="@extentZ"/>
            </xsl:attribute>
            <xsl:element name="meshX">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="LinMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@pointsX"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
            <xsl:element name="meshY">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="LinMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@pointsY"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
            <xsl:element name="meshZ">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="LinMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@pointsZ"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # replace GenLinCubDustGridStructure by CartesianDustGrid
    ('''//GenLinCubDustGridStructure''',
    '''
    <xsl:template match="GenLinCubDustGridStructure">
        <xsl:element name="CartesianDustGrid">
            <xsl:apply-templates select="@*[not(starts-with(name(),'points'))]"/>
            <xsl:element name="meshX">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="LinMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@pointsX"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
            <xsl:element name="meshY">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="LinMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@pointsY"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
            <xsl:element name="meshZ">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="LinMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@pointsZ"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # replace PowCubDustGridStructure by CartesianDustGrid
    ('''//PowCubDustGridStructure''',
    '''
    <xsl:template match="PowCubDustGridStructure">
        <xsl:element name="CartesianDustGrid">
            <xsl:apply-templates select="@*[starts-with(name(),'write')]"/>
            <xsl:attribute name="minX">
                <xsl:value-of select="concat('-',@extentX)"/>
            </xsl:attribute>
            <xsl:attribute name="maxX">
                <xsl:value-of select="@extentX"/>
            </xsl:attribute>
            <xsl:attribute name="minY">
                <xsl:value-of select="concat('-',@extentY)"/>
            </xsl:attribute>
            <xsl:attribute name="maxY">
                <xsl:value-of select="@extentY"/>
            </xsl:attribute>
            <xsl:attribute name="minZ">
                <xsl:value-of select="concat('-',@extentZ)"/>
            </xsl:attribute>
            <xsl:attribute name="maxZ">
                <xsl:value-of select="@extentZ"/>
            </xsl:attribute>
            <xsl:element name="meshX">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="SymPowMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@pointsX"/>
                    </xsl:attribute>
                    <xsl:attribute name="ratio">
                        <xsl:value-of select="@ratioX"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
            <xsl:element name="meshY">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="SymPowMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@pointsY"/>
                    </xsl:attribute>
                    <xsl:attribute name="ratio">
                        <xsl:value-of select="@ratioY"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
            <xsl:element name="meshZ">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="SymPowMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@pointsZ"/>
                    </xsl:attribute>
                    <xsl:attribute name="ratio">
                        <xsl:value-of select="@ratioZ"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # replace AdaptiveMeshDustGridStructure by AdaptiveMeshDustGrid
    ('''//AdaptiveMeshDustGridStructure''',
    '''
    <xsl:template match="AdaptiveMeshDustGridStructure">
        <xsl:element name="AdaptiveMeshDustGrid">
            <xsl:apply-templates select="@*"/>
        </xsl:element>
    </xsl:template>
    '''),

    # replace Voronoi/BinTree/OctTree/ParticleTree-DustGridStructure by -DustGrid
    ('''//VoronoiDustGridStructure|//BinTreeDustGridStructure|//OctTreeDustGridStructure|//ParticleTreeDustGridStructure''',
    '''
    <xsl:template match="VoronoiDustGridStructure|BinTreeDustGridStructure|OctTreeDustGridStructure|ParticleTreeDustGridStructure">
        <xsl:element name="{substring-before(name(),'Structure')}">
            <xsl:apply-templates select="@*[not(starts-with(name(),'extent'))]"/>
            <xsl:attribute name="minX">
                <xsl:value-of select="concat('-',@extentX)"/>
            </xsl:attribute>
            <xsl:attribute name="maxX">
                <xsl:value-of select="@extentX"/>
            </xsl:attribute>
            <xsl:attribute name="minY">
                <xsl:value-of select="concat('-',@extentY)"/>
            </xsl:attribute>
            <xsl:attribute name="maxY">
                <xsl:value-of select="@extentY"/>
            </xsl:attribute>
            <xsl:attribute name="minZ">
                <xsl:value-of select="concat('-',@extentZ)"/>
            </xsl:attribute>
            <xsl:attribute name="maxZ">
                <xsl:value-of select="@extentZ"/>
            </xsl:attribute>
            <xsl:apply-templates select="node()"/>
        </xsl:element>
    </xsl:template>
    '''),

    # replace TwoPhaseDustGridStructure by TwoPhaseDustGrid
    ('''//TwoPhaseDustGridStructure''',
    '''
    <xsl:template match="TwoPhaseDustGridStructure">
        <xsl:element name="TwoPhaseDustGrid">
            <xsl:apply-templates select="@*[starts-with(name(),'write')]"/>
            <xsl:apply-templates select="@*[starts-with(name(),'filli')]"/>
            <xsl:apply-templates select="@*[starts-with(name(),'contr')]"/>
            <xsl:attribute name="minX">
                <xsl:value-of select="concat('-',@extentX)"/>
            </xsl:attribute>
            <xsl:attribute name="maxX">
                <xsl:value-of select="@extentX"/>
            </xsl:attribute>
            <xsl:attribute name="minY">
                <xsl:value-of select="concat('-',@extentY)"/>
            </xsl:attribute>
            <xsl:attribute name="maxY">
                <xsl:value-of select="@extentY"/>
            </xsl:attribute>
            <xsl:attribute name="minZ">
                <xsl:value-of select="concat('-',@extentZ)"/>
            </xsl:attribute>
            <xsl:attribute name="maxZ">
                <xsl:value-of select="@extentZ"/>
            </xsl:attribute>
            <xsl:element name="meshX">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="LinMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@pointsX"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
            <xsl:element name="meshY">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="LinMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@pointsY"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
            <xsl:element name="meshZ">
                <xsl:attribute name="type">
                    <xsl:value-of select="'MoveableMesh'"/>
                </xsl:attribute>
                <xsl:element name="LinMesh">
                    <xsl:attribute name="numBins">
                        <xsl:value-of select="@pointsZ"/>
                    </xsl:attribute>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
    '''),

    # replace extent attributes on Instruments by fieldOfView attributes
    ('''//SimpleInstrument[@extentX]|//FrameInstrument[@extentX]|//FullInstrument[@extentX]|//InstrumentFrame[@extentX]''',
    '''
    <xsl:template match="SimpleInstrument|FrameInstrument|FullInstrument|InstrumentFrame">
        <xsl:element name="{name()}">
            <xsl:apply-templates select="@*[not(starts-with(name(),'extent'))]"/>
            <xsl:attribute name="fieldOfViewX">
                <xsl:value-of select="concat(2*@pixelsX div (@pixelsX -1)*substring-before(normalize-space(@extentX),' '), ' ', substring-after(normalize-space(@extentX),' '))"/>
            </xsl:attribute>
            <xsl:attribute name="fieldOfViewY">
                <xsl:value-of select="concat(2*@pixelsY div (@pixelsY -1)*substring-before(normalize-space(@extentY),' '), ' ', substring-after(normalize-space(@extentY),' '))"/>
            </xsl:attribute>
        </xsl:element>
    </xsl:template>
    '''),

    # remove scattWavelength attribute on Oligo/Pan-MonteCarloSimulation
    ('''//OligoMonteCarloSimulation[@scattWavelength]|//PanMonteCarloSimulation[@scattWavelength]''',
    '''
    <xsl:template match="OligoMonteCarloSimulation|PanMonteCarloSimulation">
        <xsl:element name="{name()}">
            <xsl:apply-templates select="@*[not(name()='scattWavelength')]"/>
            <xsl:apply-templates select="node()"/>
        </xsl:element>
    </xsl:template>
    '''),

    # - - - - - - - - - - - -

    # git 580-f9e4296 (Oct 23, 2015): replace extents on geometries, dust distributions and stellar components by boxes
    ('''//AdaptiveMeshGeometry[@extentX]|//CropGeometryDecorator[@extentX]|//FoamGeometryDecorator[@extentX]|//UniformCuboidGeometry[@extentX]|//VoronoiGeometry[@extentX]|'''+
     '''//AdaptiveMeshDustDistribution[@extentX]|//VoronoiDustDistribution[@extentX]|//AdaptiveMeshStellarComp[@extentX]|//VoronoiStellarComp[@extentX]''',
    '''
    <xsl:template match="AdaptiveMeshGeometry|CropGeometryDecorator|FoamGeometryDecorator|UniformCuboidGeometry|VoronoiGeometry|AdaptiveMeshDustDistribution|VoronoiDustDistribution|AdaptiveMeshStellarComp|VoronoiStellarComp">
        <xsl:element name="{name()}">
            <xsl:apply-templates select="@*[not(starts-with(name(),'extent'))]"/>
            <xsl:attribute name="minX">
                <xsl:value-of select="concat('-',@extentX)"/>
            </xsl:attribute>
            <xsl:attribute name="maxX">
                <xsl:value-of select="@extentX"/>
            </xsl:attribute>
            <xsl:attribute name="minY">
                <xsl:value-of select="concat('-',@extentY)"/>
            </xsl:attribute>
            <xsl:attribute name="maxY">
                <xsl:value-of select="@extentY"/>
            </xsl:attribute>
            <xsl:attribute name="minZ">
                <xsl:value-of select="concat('-',@extentZ)"/>
            </xsl:attribute>
            <xsl:attribute name="maxZ">
                <xsl:value-of select="@extentZ"/>
            </xsl:attribute>
            <xsl:apply-templates select="node()"/>
        </xsl:element>
    </xsl:template>
    '''),

    # git 652-88a35b7 (Mar 16, 2016): replace Crop/CavityGeometryDecorator classes by ClipGeometryDecorator subclasses
    ('''//CropGeometryDecorator''',
    '''
    <xsl:template match="CropGeometryDecorator">
        <xsl:element name="BoxClipGeometryDecorator">
            <xsl:attribute name="remove">
                <xsl:value-of select="'Outside'"/>
            </xsl:attribute>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    '''),
    ('''//SpheCropGeometryDecorator''',
    '''
    <xsl:template match="SpheCropGeometryDecorator">
        <xsl:element name="SphericalClipGeometryDecorator">
            <xsl:attribute name="remove">
                <xsl:value-of select="'Outside'"/>
            </xsl:attribute>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    '''),
    ('''//SphericalCavityGeometryDecorator''',
    '''
    <xsl:template match="SphericalCavityGeometryDecorator">
        <xsl:element name="SphericalClipGeometryDecorator">
            <xsl:attribute name="remove">
                <xsl:value-of select="'Inside'"/>
            </xsl:attribute>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    '''),
    ('''//CylindricalCavityGeometryDecorator''',
    '''
    <xsl:template match="CylindricalCavityGeometryDecorator">
        <xsl:element name="CylindricalClipGeometryDecorator">
            <xsl:attribute name="remove">
                <xsl:value-of select="'Inside'"/>
            </xsl:attribute>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:element>
    </xsl:template>
    '''),

    # terminate the list of SKIRT 7 definitions
    ]

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # ***** Transition to SKIRT 8 *****
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # convert CubBackgroundGeometry 'extent' attribute (= half of the edge length) to corresponding 'edgeLength'
    definitions.append((
        '''//CubBackgroundGeometry/@extent''',
        '''
        <xsl:template match="//CubBackgroundGeometry/@extent">
            <xsl:attribute name="edgeLength">
                <xsl:value-of select="concat(2*substring-before(normalize-space(),' '), ' ', substring-after(normalize-space(),' '))"/>
            </xsl:attribute>
        </xsl:template>
        '''))

    # Because of the large number of attribute name changes, we first provide a list of those changes
    # and then dynamically add appropriate xslt templates to the list of upgrade definitions
    # List entries contain: concrete class name, old property name, new property name
    scalarNameChanges = [
        ( "BinTreeDustGrid", "maxDensDispFraction", "maxDensityDispersion" ),
        ( "BinTreeDustGrid", "sampleCount", "numSamples" ),
        ( "BrokenExpDiskGeometry", "axialScale", "scaleHeight" ),
        ( "BrokenExpDiskGeometry", "radialScaleInner", "scaleLengthInner" ),
        ( "BrokenExpDiskGeometry", "radialScaleOuter", "scaleLengthOuter" ),
        ( "ClumpyGeometryDecorator", "clumpCount", "numClumps" ),
        ( "ClumpyGeometryDecorator", "cutoff", "cutoffClumps" ),
        ( "ConicalShellGeometry", "anisoRadius", "reshapeInnerRadius" ),
        ( "ConicalShellGeometry", "cutRadius", "cutoffRadius" ),
        ( "ConicalShellGeometry", "expon", "exponent" ),
        ( "ConicalShellGeometry", "inAngle", "minAngle" ),
        ( "ConicalShellGeometry", "outAngle", "maxAngle" ),
        ( "Cylinder2DDustGrid", "maxR", "maxRadius" ),
        ( "CylindricalClipGeometryDecorator", "radius", "clipRadius" ),
        ( "Dim1DustLib", "entries", "numFieldStrengths" ),
        ( "Dim2DustLib", "pointsTemperature", "numTemperatures" ),
        ( "Dim2DustLib", "pointsWavelength", "numWavelengths" ),
        ( "DustMixPopulation", "subPops", "numGrainSizes" ),
        ( "EinastoGeometry", "radius", "halfMassRadius" ),
        ( "ElectronDustMix", "circularPolarization", "addCircularPolarization" ),
        ( "EnstatiteGrainComposition", "type", "grainType" ),
        ( "ExpDiskGeometry", "axialScale", "scaleHeight" ),
        ( "ExpDiskGeometry", "axialTrunc", "maxZ" ),
        ( "ExpDiskGeometry", "innerRadius", "minRadius" ),
        ( "ExpDiskGeometry", "radialScale", "scaleLength" ),
        ( "ExpDiskGeometry", "radialTrunc", "maxRadius" ),
        ( "ForsteriteGrainComposition", "type", "grainType" ),
        ( "FrameInstrument", "pixelsX", "numPixelsX" ),
        ( "FrameInstrument", "pixelsY", "numPixelsY" ),
        ( "FullInstrument", "pixelsX", "numPixelsX" ),
        ( "FullInstrument", "pixelsY", "numPixelsY" ),
        ( "FullInstrument", "scatteringLevels", "numScatteringLevels" ),
        ( "GammaGeometry", "scale", "scaleLength" ),
        ( "HyperboloidGeometry", "anisoRadius", "reshapeInnerRadius" ),
        ( "HyperboloidGeometry", "cutRadius", "cutoffRadius" ),
        ( "HyperboloidGeometry", "openAngle", "openingAngle" ),
        ( "HyperboloidShellGeometry", "openInAngle", "innerOpeningAngle" ),
        ( "HyperboloidShellGeometry", "openOutAngle", "outerOpeningAngle" ),
        ( "HyperboloidShellGeometry", "radialOutExtent", "outerRadialExtent" ),
        ( "HyperboloidShellGeometry", "realInAxis", "innerRealAxis" ),
        ( "HyperboloidShellGeometry", "realOutAxis", "outerRealAxis" ),
        ( "InstrumentFrame", "pixelsX", "numPixelsX" ),
        ( "InstrumentFrame", "pixelsY", "numPixelsY" ),
        ( "LogNormalGrainSizeDistribution", "factor", "proportionalityFactor" ),
        ( "LogWavelengthGrid", "points", "numWavelengths" ),
        ( "MRNDustMix", "graphitePops", "numGraphiteSizes" ),
        ( "MRNDustMix", "silicatePops", "numSilicateSizes" ),
        ( "ModifiedLogNormalGrainSizeDistribution", "factor", "proportionalityFactor" ),
        ( "ModifiedLogNormalGrainSizeDistribution", "y0", "firstMixingParameter" ),
        ( "ModifiedLogNormalGrainSizeDistribution", "y1", "secondMixingParameter" ),
        ( "ModifiedPowerLawGrainSizeDistribution", "ac", "scaleExponentialDecay" ),
        ( "ModifiedPowerLawGrainSizeDistribution", "alpha", "powerLawIndex" ),
        ( "ModifiedPowerLawGrainSizeDistribution", "at", "turnOffPoint" ),
        ( "ModifiedPowerLawGrainSizeDistribution", "au", "scaleCurvature" ),
        ( "ModifiedPowerLawGrainSizeDistribution", "eta", "exponentCurvature" ),
        ( "ModifiedPowerLawGrainSizeDistribution", "factor", "proportionalityFactor" ),
        ( "ModifiedPowerLawGrainSizeDistribution", "gamma", "exponentExponentialDecay" ),
        ( "ModifiedPowerLawGrainSizeDistribution", "zeta", "strengthCurvature" ),
        ( "NestedLogWavelengthGrid", "maxWavelength", "maxWavelengthBaseGrid" ),
        ( "NestedLogWavelengthGrid", "minWavelength", "minWavelengthBaseGrid" ),
        ( "NestedLogWavelengthGrid", "points", "numWavelengthsBaseGrid" ),
        ( "NestedLogWavelengthGrid", "pointsSubGrid", "numWavelengthsSubGrid" ),
        ( "OctTreeDustGrid", "barycentric", "useBarycentric" ),
        ( "OctTreeDustGrid", "maxDensDispFraction", "maxDensityDispersion" ),
        ( "OctTreeDustGrid", "sampleCount", "numSamples" ),
        ( "OligoDustSystem", "sampleCount", "numSamples" ),
        ( "OligoMonteCarloSimulation", "packages", "numPackages" ),
        ( "PanDustSystem", "cycles", "numCycles" ),
        ( "PanDustSystem", "sampleCount", "numSamples" ),
        ( "PanDustSystem", "selfAbsorption", "includeSelfAbsorption" ),
        ( "PanMonteCarloSimulation", "packages", "numPackages" ),
        ( "ParaboloidGeometry", "openAngle", "openingAngle" ),
        ( "ParaboloidShellGeometry", "offsetInZ", "innerOffsetZ" ),
        ( "ParaboloidShellGeometry", "offsetOutZ", "outerOffsetZ" ),
        ( "ParaboloidShellGeometry", "openInAngle", "innerOpeningAngle" ),
        ( "ParaboloidShellGeometry", "openOutAngle", "outerOpeningAngle" ),
        ( "ParaboloidShellGeometry", "radialInExtent", "innerRadialExtent" ),
        ( "ParticleTreeDustGrid", "extraLevels", "numExtraLevels" ),
        ( "PegaseSED", "type", "spectralType" ),
        ( "PerspectiveInstrument", "pixelsX", "numPixelsX" ),
        ( "PerspectiveInstrument", "pixelsY", "numPixelsY" ),
        ( "PlummerGeometry", "scale", "scaleLength" ),
        ( "PowerLawGrainSizeDistribution", "factor", "proportionalityFactor" ),
        ( "PseudoSersicGeometry", "radius", "effectiveRadius" ),
        ( "ReadFitsGeometry", "axialScale", "scaleHeight" ),
        ( "ReadFitsGeometry", "xcenter", "centerX" ),
        ( "ReadFitsGeometry", "xelements", "numPixelsX" ),
        ( "ReadFitsGeometry", "ycenter", "centerY" ),
        ( "ReadFitsGeometry", "yelements", "numPixelsY" ),
        ( "RingGeometry", "radius", "ringRadius" ),
        ( "RotateGeometryDecorator", "euleralpha", "eulerAlpha" ),
        ( "RotateGeometryDecorator", "eulerbeta", "eulerBeta" ),
        ( "RotateGeometryDecorator", "eulergamma", "eulerGamma" ),
        ( "SPHDustDistribution", "maximumTemperature", "maxTemperature" ),
        ( "SPHGeometry", "maximumTemperature", "maxTemperature" ),
        ( "SPHStellarComp", "velocity", "importVelocity" ),
        ( "SersicGeometry", "radius", "effectiveRadius" ),
        ( "ShellGeometry", "expon", "exponent" ),
        ( "SimpleInstrument", "pixelsX", "numPixelsX" ),
        ( "SimpleInstrument", "pixelsY", "numPixelsY" ),
        ( "SingleGrainSizeDistribution", "factor", "proportionalityFactor" ),
        ( "SpheBackgroundGeometry", "radius", "backgroundRadius" ),
        ( "Sphere1DDustGrid", "maxR", "maxRadius" ),
        ( "Sphere2DDustGrid", "maxR", "maxRadius" ),
        ( "SphericalAdaptiveMeshDustDistribution", "innerRadius", "minRadius" ),
        ( "SphericalAdaptiveMeshDustDistribution", "outerRadius", "maxRadius" ),
        ( "SphericalClipGeometryDecorator", "radius", "clipRadius" ),
        ( "SpiralStructureGeometryDecorator", "arms", "numArms" ),
        ( "SpiralStructureGeometryDecorator", "perturbWeight", "perturbationWeight" ),
        ( "SpiralStructureGeometryDecorator", "phase", "phaseZeroPoint" ),
        ( "SpiralStructureGeometryDecorator", "pitch", "pitchAngle" ),
        ( "SpiralStructureGeometryDecorator", "radius", "radiusZeroPoint" ),
        ( "StellarSurfaceGeometry", "radius", "stellarRadius" ),
        ( "TTauriDiskGeometry", "axialScale", "scaleHeight" ),
        ( "TTauriDiskGeometry", "radialScale", "scaleLength" ),
        ( "ThemisDustMix", "enstatitePops", "numEnstatiteSizes" ),
        ( "ThemisDustMix", "forsteritePops", "numForsteriteSizes" ),
        ( "ThemisDustMix", "hydrocarbonPops", "numHydrocarbonSizes" ),
        ( "TorusGeometry", "anisoRadius", "reshapeInnerRadius" ),
        ( "TorusGeometry", "cutRadius", "cutoffRadius" ),
        ( "TorusGeometry", "expon", "exponent" ),
        ( "TorusGeometry", "openAngle", "openingAngle" ),
        ( "TriaxialGeometryDecorator", "yFlattening", "flatteningY" ),
        ( "TriaxialGeometryDecorator", "zFlattening", "flatteningZ" ),
        ( "TrustDustMix", "PAHPops", "numPAHSizes" ),
        ( "TrustDustMix", "graphitePops", "numGraphiteSizes" ),
        ( "TrustDustMix", "silicatePops", "numSilicateSizes" ),
        ( "WeingartnerDraineDustMix", "PAHPops", "numPAHSizes" ),
        ( "WeingartnerDraineDustMix", "graphitePops", "numGraphiteSizes" ),
        ( "WeingartnerDraineDustMix", "silicatePops", "numSilicateSizes" ),
        ( "ZubkoDustMix", "PAHPops", "numPAHSizes" ),
        ( "ZubkoDustMix", "graphitePops", "numGraphiteSizes" ),
        ( "ZubkoDustMix", "silicatePops", "numSilicateSizes" ),
        ( "ZubkoGraphiteGrainSizeDistribution", "factor", "proportionalityFactor" ),
        ( "ZubkoPAHGrainSizeDistribution", "factor", "proportionalityFactor" ),
        ( "ZubkoSilicateGrainSizeDistribution", "factor", "proportionalityFactor" ),
    ]

    compoundNameChanges = [
        ( "Cylinder2DDustGrid", "meshR", "meshRadial" ),
        ( "Sphere1DDustGrid", "meshR", "meshRadial" ),
        ( "Sphere2DDustGrid", "meshR", "meshRadial" ),
        ( "Sphere2DDustGrid", "meshTheta", "meshPolar" ),
    ]

    # add the xslt templates for scalar properties
    for elementName, oldName, newName in scalarNameChanges:
        definitions.append(('''//{0}/@{1}'''.format(elementName,oldName),
                            '''
                            <xsl:template match="//{0}/@{1}">
                                <xsl:attribute name="{2}">
                                    <xsl:value-of select="."/>
                                </xsl:attribute>
                            </xsl:template>
                            '''.format(elementName,oldName,newName)))

    # add the xslt templates for compound properties
    for elementName, oldName, newName in compoundNameChanges:
        definitions.append(('''//{0}/{1}'''.format(elementName,oldName),
                            '''
                            <xsl:template match="//{0}/{1}">
                                <xsl:element name="{2}">
                                    <xsl:apply-templates select="@*|node()"/>
                                </xsl:element>
                            </xsl:template>
                            '''.format(elementName,oldName,newName)))

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # ***** SKIRT 8 upgrades *****
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # start the list of definitions for upgrades after the transition to SKIRT 8
    definitions += [

    # git e94a2f8: upgrade Themis dust model to 2017 version using DustEM input files
    ('''//ThemisDustMix/@numEnstatiteSizes|//ThemisDustMix/@numForsteriteSizes''',
    '''
    <xsl:template match="//ThemisDustMix/@numEnstatiteSizes|//ThemisDustMix/@numForsteriteSizes">
        <xsl:attribute name="numSilicateSizes">
            <xsl:value-of select="."/>
        </xsl:attribute>
    </xsl:template>
    '''),

    # git 11dc773: replace numCycles by min/maxIterations (parameters controlling self-absorption)
    ('''//PanDustSystem/@numCycles''',
    '''
    <xsl:template match="//PanDustSystem/@numCycles">
        <xsl:if test="number()>0">
             <xsl:attribute name="minIterations">
                <xsl:value-of select="."/>
            </xsl:attribute>
            <xsl:attribute name="maxIterations">
               <xsl:value-of select="."/>
           </xsl:attribute>
        </xsl:if>
    </xsl:template>
    '''),

    # terminate the list of SKIRT 8 definitions
    ]

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    return definitions

# -----------------------------------------------------------------
